import type { Metadata } from 'next'

import { AccountingNavBar } from '@/components/accounting/nav-bar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <AccountingNavBar />

      <div className="p-3">{children}</div>
    </>
  )
}
