import type { Metadata } from 'next'

import { AppSidebar } from '@/components/app-sidebar'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className="">
                <AppSidebar>{children}</AppSidebar>
            </body>
        </html>
    )
}
